// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)


String report;
float ac_mains_voltage;
float humidity;
float pressure;
float temperature;
bool fireAlertStatus;
bool smokeAlertStatus;

void initProperties(){

  ArduinoCloud.addProperty(report, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ac_mains_voltage, READ, ON_CHANGE, NULL, 1);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(pressure, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temperature, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(fireAlertStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(smokeAlertStatus, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
